### ISSUE TITLE
Research External API´s

### ISSUE THREAD

**Issue by wbgneto** [wbgneto/ez.api#12]
We need to find out which API to use to create our data visualization.

Please each one of you post here a resource that you think we can use.

Do this by next Tuesday (February 4th).

@jyotSarup 
@sweera 
@saebomp 
@saebyeolp 
@mcalv
@NazaninAhmadii

**Comment by jyotSarup** [comment]
https://www.reso.org/web-api-developer-reference-server/

**Comment by jyotSarup** [comment]
https://rapidapi.com/apidojo/api/realtor/endpoints

**Comment by jyotSarup** [comment]
https://www.oodle.com/info/developer/oodle-api/

**Comment by sweera** [comment]
1. https://www.programmableweb.com/api/zillow
2. http://www.retsrabbit.com/
3. https://www.attomdata.com/solutions/property-data-api/

**Comment by heloysatancredo** [comment]
City of Vancouver – Open data Portal (https://opendata.vancouver.ca/)

Local Areas Boundaries
https://opendata.vancouver.ca/explore/dataset/local-area-boundary/api/

Schools
https://opendata.vancouver.ca/explore/dataset/schools/api/

Cultural Spaces
https://opendata.vancouver.ca/explore/dataset/cultural-spaces/api/?disjunctive.type&disjunctive.primary_use&disjunctive.ownership

Libraries
https://opendata.vancouver.ca/explore/dataset/libraries/api/

Community Centers
https://opendata.vancouver.ca/explore/dataset/community-centres/api/

Parks
https://opendata.vancouver.ca/explore/dataset/parks/api/

Disability Parking
https://opendata.vancouver.ca/explore/dataset/disability-parking/api/

Bikeways
https://opendata.vancouver.ca/explore/dataset/bikeways/api/?disjunctive.year_of_construction

Electric vehicle charging stations
https://opendata.vancouver.ca/explore/dataset/electric-vehicle-charging-stations/api/

**Comment by saebyeolp** [comment]
https://www.walkscore.com/professional/walk-score-apis.php
Walk Score

https://rapidapi.com/urban-algorithmics/api/urban-geo-data/details
Urban Geo Data

**Comment by saebomp** [comment]
https://openlayers.org/en/latest/apidoc/
https://catalogue.data.gov.bc.ca/dataset/bc-address-geocoder-web-service

**Comment by wbgneto** [comment]
Thank you guys!
